language: python
install:
- pip install mkdocs mkdocs-material
script:
- mkdocs build --verbose --clean
deploy:
 provider: pages
 skip_cleanup: true
 github_token: $GITHUB_TOKEN
 local_dir: site
 name: $BOT_NAME
 email: $BOT_EMAIL
 on:
   branch: master
